### ISSUE TITLE
# WARN: хранение FEDM_ISCReaderModule* в void*

### ISSUE THREAD

**Issue by ghost** [become-iron/RFID_module#1]
Hi,

unfortunately I do net get it, how to solve this issue,

# WARN: хранение FEDM_ISCReaderModule* в void*

I appreciate any support.
Many Thanks,
Luke

**Comment by become-iron** [comment]
Hi!

It's not an issue. Really, just a note

**Comment by ghost** [comment]
Any idea why I am having an error at that part?

**Comment by become-iron** [comment]
No idea. You didn't even show any logs. The project is unmaintained currently by the way

**Comment by ghost** [comment]
Traceback (most recent call last):

  File "C:\xxxxxRFID_module-master\module\reader.py", line 9, in <module>
    RFID_LIB.new_reader.restype = ctypes.c_void_p  # WARN: хранение FEDM_ISCReaderModule* в void*

  File "C:\xxxxx\WinPython\python-3.9.4.amd64\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)

  File "C:\xxxx\WinPython\python-3.9.4.amd64\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

AttributeError: function 'new_reader' not found

**Comment by become-iron** [comment]
There are some docs, considering build of project: https://rfid-module.readthedocs.io/start.html. Maybe it could help you in some way

**Comment by become-iron** [comment]
For example, I see that you use Python 3.9.4 x64, but I used Python 3.6.0 x32

**Comment by become-iron** [comment]
It matters, whether it's x64 or x32
